#!/bin/sh
#
# tapd    Startup script for the tapd
#
# chkconfig: 2345 95 5
# description: tapd, providing taps to your datacenter.
# pidfile: /var/run/tapd.pid

# processname: lighttpd
# config: /etc/tapd/options.conf
#

# Source function library
. /etc/rc.d/init.d/functions


if [ -f /etc/sysconfig/lighttpd ]; then
	. /etc/sysconfig/lighttpd
fi

prog="tapd"
lighttpd="/usr/sbin/tapd"
RETVAL=0
PID_FILE=/var/run/tapd.pid
LIGHTTPD_CONF_PATH=/etc/tapd/options.conf 

start() {
	echo -n $"Starting $prog: "
	daemon $lighttpd -f $LIGHTTPD_CONF_PATH
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc $lighttpd
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

reload() {
	echo -n $"Reloading $prog: "
	killproc $lighttpd -HUP
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	condrestart)
		if [ -f /var/lock/subsys/$prog ]; then
			stop
			start
		fi
		;;
	reload)
		reload
		;;
	status)
		status $lighttpd
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|condrestart|reload|status}"
		RETVAL=1
esac

exit $RETVAL